// <auto-generated />
using LitovchenkoApp.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LitovchenkoApp.Migrations
{
    [DbContext(typeof(DbAppContext))]
    [Migration("20230401100506_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("LitovchenkoApp.Db.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "USA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Great Britain"
                        });
                });

            modelBuilder.Entity("LitovchenkoApp.Db.Models.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Saint-Petersburg"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "New-York"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Washington"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "London"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 3,
                            Name = "Liverpol"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Leicester"
                        });
                });

            modelBuilder.Entity("LitovchenkoApp.Db.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LitovchenkoApp.Db.Models.Province", b =>
                {
                    b.HasOne("LitovchenkoApp.Db.Models.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("LitovchenkoApp.Db.Models.User", b =>
                {
                    b.HasOne("LitovchenkoApp.Db.Models.Province", "Province")
                        .WithMany("Users")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("LitovchenkoApp.Db.Models.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("LitovchenkoApp.Db.Models.Province", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
